version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-healthy7s-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_LOCAL_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_LOCAL_NAME}
      # MYSQL_USER: ${DOCKER_LOCAL_USER}
      # MYSQL_PASSWORD: ${DOCKER_LOCAL_PASSWORD}
    ports:
      - "${DOCKER_SQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - healthy-api-network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - healthy-api-network

  healthy-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthy-api
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      APPLICATION_NAME: ${APPLICATION_NAME}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: ${DOCKER_SQL_URL}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_LOCAL_USER}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_LOCAL_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      HIKARI_POOL_NAME: ${HIKARI_POOL_NAME}
      LOG_LEVEL_API: DEBUG
      LOG_LEVEL_JDBC: DEBUG
      SPRING_PROFILES_ACTIVE: docker
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - healthy-api-network

volumes:
  mysql-data:
  redis-data:

networks:
  healthy-api-network:
    driver: bridge
    name: healthy-api-network